ssl_certificate     /etc/letsencrypt/live/server.henriquesebastiao.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/server.henriquesebastiao.com/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
error_page 497 =301 https://$host:$server_port$request_uri;
add_header Strict-Transport-Security "max-age=31536000" always;