version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    ignore:
      - dependency-name: "postgres:*"