version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *" # Às 0h do dia 1 de cada mês
      timezone: "America/Cuiaba"
    assignees:
      - "henriquesebastiao"
    ignore:
      - dependency-name: "postgres:*"