version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    ignore:
      - dependency-name: "docker.io/library/postgres:*"
        # Ignore versions of Postgres that are equal to or greater than 18
        versions: [ ">=18" ]