config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  keyid: 6F5C3CD702976E14
trans_install:
  _decrypt: gpg -q -d {0} > {1}
trans_update:
  _encrypt: gpg -q -r {{@@ keyid @@}} --armor --no-tty -o {1} -e {0}
dotfiles:
  f_config.yaml:
    src: config/code-server/config.yaml
    dst: ~/.config/code-server/config.yaml
    chmod: '644'
    trans_install: _decrypt
    trans_update: _encrypt
  f_env:
    src: homelab/.env
    dst: ~/homelab/.env
    chmod: '664'
    trans_install: _decrypt
    trans_update: _encrypt
  f_settings.json:
    src: local/share/code-server/User/settings.json
    dst: ~/.local/share/code-server/User/settings.json
  f_bpytop.conf:
    src: config/bpytop/bpytop.conf
    dst: ~/.config/bpytop/bpytop.conf
    chmod: '664'
  f_config.yml:
    src: config/gh/config.yml
    dst: ~/.config/gh/config.yml
    chmod: '600'
  f_htoprc:
    src: config/htop/htoprc
    dst: ~/.config/htop/htoprc
    chmod: '600'
  f_config.conf:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
  f_spaceship.zsh:
    src: config/spaceship.zsh
    dst: ~/.config/spaceship.zsh
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
    trans_install: _decrypt
    trans_update: _encrypt
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_profile:
    src: profile
    dst: ~/.profile
    chmod: '644'
    trans_install: _decrypt
    trans_update: _encrypt
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    trans_install: _decrypt
    trans_update: _encrypt
  f_authorized_keys:
    src: ssh/authorized_keys
    dst: ~/.ssh/authorized_keys
    chmod: '600'
    trans_install: _decrypt
    trans_update: _encrypt
  f_config.toml:
    src: config/atuin/config.toml
    dst: ~/.config/atuin/config.toml
    chmod: '600'
profiles:
  server:
    dotfiles:
    - f_config.yaml
    - f_env
    - f_settings.json
    - f_bpytop.conf
    - f_config.yml
    - f_htoprc
    - f_config.conf
    - f_spaceship.zsh
    - f_aliases
    - f_bashrc
    - f_gitconfig
    - f_profile
    - f_zshrc
    - f_authorized_keys
    - f_config.toml
