services:
  beaverhabits:
    container_name: beaverhabits
    user: 1000:1000 # User permissions of your docker or default user.
    environment:
      # See the link below to find all the environment variables
      # https://github.com/daya0576/beaverhabits/wiki/Development#options
      - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
      - TRUSTED_LOCAL_EMAIL=your@email.com # Skip authentication
      - INDEX_HABIT_DATE_COLUMNS=5 # Customize the date columns for the index page.
      - ENABLE_IOS_STANDALONE=true
    volumes:
      - /home/hick/homelab/containers/beaverhabits/data/:/app/.user/ # Change directory to match your docker file scheme.
    ports:
      - 8023:8080
    restart: unless-stopped
    image: daya0576/beaverhabits:latest
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8005:8080
  
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    ports:
      - 8018:8200
    volumes:
      - /home/hick/homelab/containers/duplicati/config:/config
      - /home/hick/backups:/backups
      - /:/source:ro
    environment:
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: server.local
      DUPLICATI__WEBSERVICE_PASSWORD: duplicati-pass
      PUID: 1000
      PGID: 1000
      SETTINGS_ENCRYPTION_KEY: duplicati-encryption-key
      TZ: "America/Cuiaba"

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0" # Run as root to avoid permission issues
    ports:
      - 8015:80
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - /home/hick:/data
    environment:
      - FB_ROOT=/data
      - FB_NOAUTH=true
  
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/glance/config:/app/config
      - /home/hick/homelab/containers/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8007:8080
    env_file: /home/hick/homelab/containers/glance/.env
  
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/hick/homelab/containers/homeassistant/data/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host  # Port 8123

  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_FILE_UPLOAD=10
    - HBOX_OPTIONS_ALLOW_ANALYTICS=false
    volumes:
      - /home/hick/homelab/containers/homebox/data:/data/
    ports:
      - 8022:7745

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - 8013:80
  
  ocular-backend:
    image: ghcr.io/simonwep/genesis:v1.4.1
    container_name: ocular-backend
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/ocular/data:/app/.data
    command: start
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_JWT_COOKIE_ALLOW_HTTP
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  ocular-frontend:
    image: ghcr.io/simonwep/ocular:v1.12.0
    container_name: ocular-frontend
    restart: unless-stopped
    environment:
      - OCULAR_DEMO

  ocular-nginx:
    image: nginx:1.26-alpine
    container_name: ocular-nginx
    restart: unless-stopped
    ports:
      - 8020:80
    volumes:
      - /home/hick/homelab/containers/ocular/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ocular-backend
      - ocular-frontend
  
  pinepods-db:
    container_name: pinepods-db
    image: postgres:latest
    environment:
      POSTGRES_DB: pinepods_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myS3curepass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/hick/homelab/containers/pinepods/data/pgdata:/var/lib/postgresql/data
    restart: always

  pinepods-valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    container_name: pinepods-valkey

  pinepods:
    image: madeofpendletonwool/pinepods:latest
    container_name: pinepods
    restart: unless-stopped
    ports:
      - "8017:8040"
    environment:
      # Basic Server Info
      SEARCH_API_URL: 'https://search.pinepods.online/api/search'
      PEOPLE_API_URL: 'https://people.pinepods.online'
      HOSTNAME: 'http://localhost:8040'
      # Default Admin User Information
      USERNAME: hick
      PASSWORD: pinepods-pass
      FULLNAME: Henrique Sebastião
      EMAIL: contato@henriquesebastiao.com
      # Database Vars
      DB_TYPE: postgresql
      DB_HOST: pinepods-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: myS3curepass
      DB_NAME: pinepods_database
      # Valkey Settings
      VALKEY_HOST: pinepods-valkey
      VALKEY_PORT: 6379
      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: false
      PUID: 1000
      PGID: 1000
      # Add timezone configuration
      TZ: "America/Cuiaba"
    volumes:
      # Mount the download and backup locations on the server
      - /home/hick/homelab/containers/pinepods/data/downloads:/opt/pinepods/downloads
      - /home/hick/homelab/containers/pinepods/data/backups:/opt/pinepods/backups
      # Timezone volumes, HIGHLY optional. Read the timezone notes below
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - pinepods-db
      - pinepods-valkey
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8009:9000
  
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - 8021:80
    environment:
      TZ: America/Cuiaba
    # Volumes store your data between container upgrades
    volumes:
      - /home/hick/homelab/containers/wallos/db:/var/www/html/db
      - /home/hick/homelab/containers/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
  portainer_data: