services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "xio3r26RRN2AV0Zqn60bLGQ6-gvsCSObt4O8_Ikk45g"
      DATABASE_URL: "postgresql://docmost:docmost-db-password@docmost-db:5432/docmost?schema=public"
      REDIS_URL: "redis://docmost-redis:6379"
    ports:
      - 8016:3000
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  docmost-db:
    image: postgres:16-alpine
    container_name: docmost-db
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost-db-password
    restart: unless-stopped
    volumes:
      - docmost_db_data:/var/lib/postgresql/data

  docmost-redis:
    image: redis:7.2-alpine
    container_name: docmost-redis
    restart: unless-stopped
    volumes:
      - docmost_redis_data:/data
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8005:8080

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0" # Run as root to avoid permission issues
    ports:
      - 8015:80
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - /home/hick:/data
    environment:
      - FB_ROOT=/data
      - FB_NOAUTH=true

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - 8013:80
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8009:9000

volumes:
  docmost:
  docmost_db_data:
  docmost_redis_data:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
  portainer_data: