services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.32.1@sha256:a52dc5db694a5bf041ce38f285dd6c6a660a4b1b21e37ad6b6746433263b2ae5
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /mnt/hd_externo/containers/audiobookshelf/audiobooks:/audiobooks
      - /mnt/hd_externo/containers/audiobookshelf/podcasts:/podcasts
      - /mnt/hd_externo/containers/audiobookshelf/config:/config
      - /mnt/hd_externo/containers/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Cuiaba
    restart: always

  calibre-web:
    image: linuxserver/calibre-web:0.6.26@sha256:68c0e408e7c307b4e0abcd8b2fadc6279d67867767a2a926eda0c921d9d6bbd8
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/hick/homelab/containers/calibre-web/config:/config
      - /home/hick/homelab/containers/calibre-web/books:/books
    ports:
      - 8024:8083
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.0.6@sha256:4815df572d135ce24c14ec3c150e482c98693bc5cc20291693b582baab8eb0bf
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8005:8080
  
  duplicati:
    image: duplicati/duplicati:2.2.0.105@sha256:580e57109d604b67fbefe1ff56d376c81435ed332e32a996229e2a2da47ab543
    container_name: duplicati
    restart: unless-stopped
    user: "0:0"
    privileged: true
    ports:
      - 8018:8200
    volumes:
      - /home/hick/homelab/containers/duplicati/config:/config
      - /home/hick/backups:/backups
      - /:/source:ro
    environment:
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: server.local;duplicati.local
      DUPLICATI__WEBSERVICE_PASSWORD: duplicati-pass
      # Executing as root to be able to read all files.
      PUID: 0
      PGID: 0
      SETTINGS_ENCRYPTION_KEY: duplicati-encryption-key
      TZ: "America/Cuiaba"
    command: ["duplicati-server", "--allow-missing-source=false"]

  filebrowser:
    image: filebrowser/filebrowser:v2.61.0@sha256:9ebcbf84ab4be44e915f2643df9a1c9b9616cd02b72be3f7735cf94e253da3f2
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0" # Run as root to avoid permission issues
    ports:
      - 8015:80
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - /home/hick:/data
      - /mnt/hd_externo:/data/hd
    environment:
      - FB_ROOT=/data
      - FB_NOAUTH=true
  
  freshrss:
    image: freshrss/freshrss:1.28.1@sha256:9100f649f5c946f589f54cdb9be7a65996528f48f691ef90eb262a0e06e5a522
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8036:80
    volumes:
      - /home/hick/homelab/containers/freshrss/data:/var/www/FreshRSS/data
      - /home/hick/homelab/containers/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/Cuiaba
      CRON_MIN: '2,32'
      FRESHRSS_INSTALL: |-
        --api-enabled
        --default-user hick
        --language pt-BR
      FRESHRSS_USER: |-
        --api-password 35218785
        --email contato@henriquesebastiao.com
        --language pt-BR
        --password 35218785
        --user hick
  
  gitea:
    image: gitea/gitea:1.25.4@sha256:17d18218be2dad1f8ed402a4f906989505c90ab8b66ee9befcecfb5d470133e7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - /home/hick/homelab/containers/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8010:3000
      - 8200:22
    depends_on:
      - gitea-db
  
  gitea-db:
    image: postgres:14.20@sha256:d508bf6220b5c7b7cd9c735d6abd5ea2e6e4e45882a29ed704f625aba32bd935
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - /home/hick/homelab/containers/gitea/postgrs/data:/var/lib/postgresql/data
  
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/glance/config:/app/config
      - /home/hick/homelab/containers/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8007:8080
    env_file: /home/hick/homelab/containers/glance/.env
  
  glance-mila:
    container_name: glance-mila
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/glance-mila/config:/app/config
      - /home/hick/homelab/containers/glance-mila/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8014:8080
    env_file: /home/hick/homelab/containers/glance-mila/.env
  
  go2rtc: # HTTP Port: 1984, RSTP Port: 8554, WebRTC Port: 8554
    image: alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae
    container_name: go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=America/Cuiaba  # timezone in logs
    volumes:
      - "/home/hick/homelab/containers/go2rtc/config:/config"   # folder for go2rtc.yaml file (edit from WebUI)

  grafana:
    image: grafana/grafana:12.4.0@sha256:b0ae311af06228bcfd4a620504b653db80f5b91e94dc3dc2a5b7dab202bcde20
    container_name: grafana
    restart: unless-stopped
    ports:
      - 8004:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
    volumes:
      - /home/hick/homelab/containers/immich/data:/data # Directory where photos and videos are stored
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 8025:2283
    depends_on:
      - immich-redis
      - immich-db
      - immich-machine-learning
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6@sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    hostname: redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-db:
    container_name: immich-postgres
    hostname: database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:8d292bdb796aa58bbbaa47fe971c8516f6f57d6a47e7172e62754feb6ed4e7b0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /home/hick/homelab/containers/immich-db/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
  
  jellyfin:
    image: jellyfin/jellyfin:10.11.6@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/hick/homelab/containers/jellyfin/config:/config
      - /home/hick/homelab/containers/jellyfin/cache:/cache
      - type: bind
        source: /home/hick/homelab/containers/jellyfin/media
        target: /media
      - type: bind
        source: /mnt/hd_externo/Videos
        target: /media/hd/Videos
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://server.local:8096
  
  komodo-mongo:
    image: mongo:8.2.5@sha256:474f5c3bf0e355bb97dafda730e725169a4d51c5578abf7be9ec7ad3fdee4481
    container_name: komodo-mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - komodo-mongo-data:/data/db
      - komodo-mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:1.19.5@sha256:a1cceb4f971443b1e9f2a767788f663d0afb6244ee2135f7fe3fd1036af37ade
    container_name: komodo-core
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    env_file: /home/hick/homelab/containers/komodo/.env
    depends_on:
      - komodo-mongo
    ports:
      - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: admin
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - /home/hick/homelab/containers/komodo/core/backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
  
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5@sha256:bd79cf960ed054fe8e02384322303e462448679b1149dde48bbef151417255b1
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    env_file: /home/hick/homelab/containers/komodo/.env
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}

  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      #TITLE: "LibreSpeed"
      #TELEMETRY: "false"
      #ENABLE_ID_OBFUSCATION: "false"
      #REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    ports:
      - 8030:8080 # webport mapping (host:container)
  
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2026.02.22@sha256:7a10c8a53a50a2c3c6e5599cab16b6be62a99a9ce9e0e48769328c6ce59b30c9
    restart: unless-stopped
    ports:
      - 8009:8081
    volumes:
      - /home/hick/homelab/containers/metube/downloads:/downloads
    environment:
      - DOWNLOAD_MODE=sequential
      - DEFAULT_THEME=dark
  
  n8n:
    image: n8nio/n8n:2.9.4@sha256:fdf1e22bc04a03e38da41da5a56ba9b9a48510f480874290ea9c180844cbdb0c
    container_name: n8n
    restart: unless-stopped
    ports:
      - 8027:443
    environment:
      - GENERIC_TIMEZONE=America/Cuiaba
      - TZ=America/Cuiaba
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.henriquesebastiao.com
      - N8N_PORT=443
      - N8N_PROTOCOL=https
    volumes:
      - /home/hick/homelab/containers/n8n/data:/home/node/.n8n
  
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    network_mode: bridge
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - 8013:8080
    environment:
      - NEXTCLOUD_DATADIR=/mnt/hd_externo/nextcloud
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8081:81' # Admin Web Port
    volumes:
      - /home/hick/homelab/containers/nginx-proxy-manager/data:/data
      - /home/hick/homelab/containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      TZ: "America/Cuiaba"
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.02.0@sha256:ee348529cea9601df86ad94d62a39cad26117e1eac9e82d8876aa0ec7fe1ba27
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8001:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Cuiaba'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD:-pihole-pass}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/home/hick/homelab/containers/pihole/etc:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
  
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4@sha256:3ee43a4d08ce4a0108e4c8150f570544a8c4a4a11e2ca95b86d46006547f80d5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
      - WEBUI_PORT=8033
      - TORRENTING_PORT=6881
    volumes:
      - /home/hick/homelab/containers/qbittorrent/config:/config
      - /home/hick/homelab/containers/qbittorrent/downloads:/downloads #optional
    ports:
      - 8033:8033
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:1.13.10@sha256:4023b3e993d3764efe41d65eb4d1be8d9ff2ad8d756eb71de35fe805882ff0b5
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
        - 8008:80
    environment:
        - PUID=1000
        - PGID=1000
        - APP_KEY=base64:h/7HdA9fMLDluj0fJ4NcG13CquLdgJTs9062lfXnmAs=
        - DB_CONNECTION=sqlite
        - APP_TIMEZONE=America/Cuiaba
        - DISPLAY_TIMEZONE=America/Cuiaba
        - APP_DEBUG=true
        - SPEEDTEST_SCHEDULE=*/30 * * * *
        # - SPEEDTEST_SERVERS=
    volumes:
        - /home/hick/homelab/containers/speedtest-tracker/config:/config
        - /home/hick/homelab/containers/speedtest-tracker/config/keys:/config/keys
    
  syncthing:
    image: syncthing/syncthing:2.0.14@sha256:6d2ab058383b533e045cf2c32fc4c6bbe87c612c92bc2aca9f552fb099b2e123
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/hick/homelab/containers/syncthing:/var/syncthing
    ports:
      - 8032:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  stirling-pdf:
    image: stirlingtools/stirling-pdf:1.6.0@sha256:1f73a8f898fe269cbbccea3be577064dd87fc4334de349fcc5b1afa1bcebf240
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - 8011:8080
    environment:
      - LANGS=pt_BR
      - DISABLE_ADDITIONAL_FEATURES=true
  
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest@sha256:28f263fe06f79ebffa5a6a6e9bd33b7a278e9342a88e0bdac812416c9f9e4361
    container_name: umami
    ports:
      - 8006:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ljVRotlgItt2dHR8TgvXvfKAfvf6AFiydmNfvKx-7oE
    depends_on:
      umami-db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umami -d umami"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.17@sha256:3d632903e6af34139a37f18055c4f1bfd9b7205ae1138f1e5e8940ddc1d176f9
    container_name: uptime-kuma
    volumes:
      - /home/hick/homelab/containers/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8026:3001
    restart: always
  
  vaultwarden:
    image: vaultwarden/server:1.35.4@sha256:43498a94b22f9563f2a94b53760ab3e710eefc0d0cac2efda4b12b9eb8690664
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.local"
    volumes:
      - /home/hick/homelab/containers/vaultwarden/data/:/data/
    ports:
      - 8019:80
  
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:7.4.7-alpine@sha256:ceeeb7555d1747bec0c392a32d6d78ae805397750a4b078f8b525e1fe72effbc
    hostname: zabbix-frontend
    container_name: zabbix-frontend
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - 8003:8080
    depends_on:
      - zabbix-server
      - zabbix-database

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.4.7-alpine@sha256:3c3c9b1a5c93442644346bfdd8cf854a491cc5a92fcfaa905a2d749b0cecbcc0
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    init: true
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - 10050:10050
    depends_on:
      - zabbix-database

  zabbix-agent:
    image: zabbix/zabbix-agent2:7.4.7-alpine@sha256:517933754215b865090e0099f58c2ff8b3f16105334632e07944eb26fe64b58b
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    init: true
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server

  zabbix-database:
    image: postgres:13.18-alpine3.20@sha256:77815c1f18ae761b0e503503a494475a03149d7ce544934ccecdbafdb3956c94
    container_name: zabbix-database
    hostname: zabbix-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - /home/hick/homelab/containers/zabbix/data:/var/lib/postgresql/data

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
  grafana-storage:
  komodo-mongo-data:
  komodo-mongo-config:
  model-cache:
  umami-db-data:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
