# Este arquivo docker compose configura todos os serviços que utilizo em produção no meu servidor pessoal
# 
# Informações úteis para administração dos containers:
# - Os containers estão dispostos em ordem alfabéticas neste arquivo
# - No início de cada serviço há um ou mais links para a documentação ou tutoriais de como configurar cada serviço

x-cloudflare-dns: &cloudflare-dns
  dns:
    - 1.1.1.1
    - 1.0.0.1

x-local-dns: &local-dns
  dns:
    - 172.16.0.2

x-timezone-env: &timezone-env
  TZ: ${TIMEZONE}

x-user-permissions: &user-permissions
  PUID: 1000
  PGID: 1000

x-restart: &restart
  restart: unless-stopped

x-docker-socket: &docker-socket
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

x-calibre-web-env: &calibre-web-env
  DOCKER_MODS: linuxserver/mods:universal-calibre #optional
  OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional

x-duplicati-env: &duplicati-env
  DUPLICATI__WEBSERVICE_PASSWORD: ${DUPLICATI__WEBSERVICE_PASSWORD}
  SETTINGS_ENCRYPTION_KEY: ${SETTINGS_ENCRYPTION_KEY}

x-filebrowser-env: &filebrowser-env
  FB_ROOT: /data
  FB_NOAUTH: true

x-freshrss-env: &freshrss-env
  CRON_MIN: '2,32'
  FRESHRSS_INSTALL: |-
    --api-enabled
    --default-user hick
    --language pt-BR
  FRESHRSS_USER: |-
    --api-password ${FRESHRSS_PASSWORD}
    --email ${FRESHRSS_EMAIL}
    --language pt-BR
    --password ${FRESHRSS_PASSWORD}
    --user ${FRESHRSS_USER}

x-jellyfin-env: &jellyfin-env
  JELLYFIN_PublishedServerUrl: http://server.local:8096

x-komodo-env: &komodo-env
  KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
  KOMODO_DATABASE_USERNAME: admin
  KOMODO_DATABASE_PASSWORD: admin
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
  COMPOSE_KOMODO_IMAGE_TAG: 2
  COMPOSE_KOMODO_BACKUPS_PATH: /etc/komodo/backups
  KOMODO_HOST: https://example.komodo.com
  KOMODO_TITLE: Komodo
  KOMODO_PERIPHERY_PUBLIC_KEY: file:/config/keys/periphery.pub
  KOMODO_LOCAL_AUTH: true
  KOMODO_INIT_ADMIN_USERNAME: admin
  KOMODO_INIT_ADMIN_PASSWORD: admin
  KOMODO_FIRST_SERVER_NAME: Local
  KOMODO_DISABLE_CONFIRM_DIALOG: false
  KOMODO_DISABLE_INIT_RESOURCES: false
  KOMODO_WEBHOOK_SECRET: a_random_secret
  KOMODO_JWT_SECRET: a_random_jwt_secret
  KOMODO_JWT_TTL: 1-day
  KOMODO_MONITORING_INTERVAL: 15-sec
  KOMODO_RESOURCE_POLL_INTERVAL: 1-hr
  KOMODO_DISABLE_USER_REGISTRATION: false
  KOMODO_ENABLE_NEW_USERS: false
  KOMODO_DISABLE_NON_ADMIN_CREATE: false
  KOMODO_TRANSPARENT_MODE: false
  KOMODO_OIDC_ENABLED: false
  KOMODO_GITHUB_OAUTH_ENABLED: false
  KOMODO_GOOGLE_OAUTH_ENABLED: false
  KOMODO_LOGGING_PRETTY: false
  KOMODO_PRETTY_STARTUP_CONFIG: false
  PERIPHERY_CORE_ADDRESS: ws://komodo-core:9120
  PERIPHERY_CONNECT_AS: Local
  PERIPHERY_ROOT_DIRECTORY: /etc/komodo
  PERIPHERY_DISABLE_TERMINALS: false
  PERIPHERY_DISABLE_CONTAINER_TERMINALS: false
  PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
  PERIPHERY_LOGGING_PRETTY: false
  PERIPHERY_PRETTY_STARTUP_CONFIG: false

x-librespeed-env: &librespeed-env
  MODE: standalone
  # TITLE: "Teste de Velocidade"
  # TELEMETRY: "false"
  # ENABLE_ID_OBFUSCATION: "false"
  # REDACT_IP_ADDRESSES: "false"
  # PASSWORD:
  # EMAIL:
  # DISABLE_IPINFO: "false"
  # IPINFO_APIKEY: "your api key"
  # DISTANCE: "km"
  # WEBPORT: 8080

x-metube-env: &metube-env
  DEFAULT_THEME: dark

x-pihole-env: &pihole-env
  # Set a password to access the web interface. Not setting one will result in a random password being assigned
  FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD:-pihole-pass}
  # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
  FTLCONF_dns_listeningMode: 'all'

x-stirling-pdf-env: &stirling-pdf-env
  LANGS: pt_BR
  DISABLE_ADDITIONAL_FEATURES: 'true'

x-vaultwarden-env: &vaultwarden-env
  DOMAIN: "https://vault.local"

x-zabbix-env: &zabbix-env
  DB_SERVER_HOST: zabbix-database
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: zabbix
  POSTGRES_DB: zabbix
  ZBX_SERVER_HOST: zabbix-server
  PHP_TZ: UTC
  ZBX_HOSTNAME: zabbix-agent

services:

  # https://github.com/linuxserver/docker-calibre-web
  # https://github.com/janeczku/calibre-web
  calibre-web:
    image: linuxserver/calibre-web:0.6.26@sha256:4711cc328bf2bb16cfcd5a98f06a0ea51a0f05b75353667aa3a8e93480454efa
    container_name: calibre-web
    environment:
      <<: [*timezone-env, *calibre-web-env, *user-permissions]
    volumes:
      - ${BASE}/calibre-web/config:/config
      - ${BASE}/calibre-web/books:/books
    ports:
      - 8024:8083
    <<: [*local-dns, *restart]

  # https://hub.docker.com/r/cloudflare/cloudflared
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    <<: [*cloudflare-dns, *restart]
  
  downtify:
    image: ghcr.io/henriquesebastiao/downtify:2.8.0@sha256:37e07e2fc05decce2dd1b2d1cbbb2a9c9b909d37f0c1cd61e868409168532b97
    container_name: downtify
    ports:
      - 8020:8000
    volumes:
      - ${BASE}/jellyfin/media/downtify:/downloads
      - ${BASE}/downtify/data:/data
    <<: [*cloudflare-dns, *restart]

  # https://dozzle.dev/guide/what-is-dozzle
  # https://github.com/amir20/dozzle
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.6.4@sha256:d834b38356027bedcc28ee77542b451a84849b73d2cd90c77be911f4a387c94d
    environment:
      <<: *user-permissions
    ports:
      - 8005:8080
    <<: [*docker-socket, *local-dns, *restart]
  
  # https://github.com/linuxserver/docker-duplicati
  # https://docs.duplicati.com/
  #
  # Diretórios de backups
  # --------------------------------------------
  # Drive                           -> Home Server
  # --------------------------------------------
  # Backups/duplicati/calibre/      -> $HOME/homelab/containers/calibre-web/
  duplicati:
    image: linuxserver/duplicati:2.3.0@sha256:d681e5213fa0871efa573856ed838d38150231df66c7de4b3dbe6980290f2571
    container_name: duplicati
    privileged: true
    ports:
      - 8018:8200
    volumes:
      - ${BASE}/duplicati/config:/config
      - /home/hick/backups:/backups
      - /:/source:rw
    environment:
      <<: [*timezone-env, *duplicati-env, *user-permissions]
    <<: [*local-dns, *restart]

  # https://filebrowser.org/installation.html
  # https://github.com/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser:v2.63.10@sha256:b0308060fb45b7767f7cf4a21d40e5e0152bad798794907769288a7a12436895
    container_name: filebrowser
    user: "0:0"
    ports:
      - 8015:80
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - /home/hick:/data
    environment:
      <<: *filebrowser-env
    <<: [*local-dns, *restart]
  
  # https://github.com/FreshRSS/FreshRSS#installation
  # https://freshrss.org/
  freshrss:
    image: freshrss/freshrss:1.29.1@sha256:ab6b363102ccdbc39f6a62db926f567c61a5289bf25ba460f1c34423d8cc1a4d
    container_name: freshrss
    ports:
      - 8036:80
    volumes:
      - ${BASE}/freshrss/data:/var/www/FreshRSS/data
      - ${BASE}/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      <<: [*freshrss-env, *timezone-env, *user-permissions]
    <<: [*local-dns, *restart]

  # https://github.com/glanceapp/glance
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
    volumes:
      - ${BASE}/glance/config:/app/config
      - ${BASE}/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8007:8080
    environment:
      <<: *user-permissions
    <<: [*cloudflare-dns, *restart]
    # env_file: ${BASE}/glance/.env

  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    ports:
      - 8004:3000
    user: '0'
    volumes:
      - ${BASE}/grafana:/var/lib/grafana
    <<: [*cloudflare-dns, *restart]
  
  # https://jellyfin.org/docs/general/installation/container/
  jellyfin:
    image: jellyfin/jellyfin:10.11.10@sha256:f66273e014b307e4ac46778845ebc1e9ee24b2e57c1fc17d5ec5ac3015649bfa
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ${BASE}/jellyfin/config:/config
      - ${BASE}/jellyfin/cache:/cache
      - type: bind
        source: ${BASE}/jellyfin/media
        target: /media
    # Optional - alternative address used for autodiscovery
    environment:
      <<: [*jellyfin-env, *user-permissions]
    <<: [*cloudflare-dns, *restart]
  
  # # https://komo.do/docs/setup/mongo
  komodo-mongo:
    image: mongo:8.2.9@sha256:a706cb4e493bcd0262f345b3b0c78732ca0e54301f0d7bbe2b66f26313ce7ccb
    container_name: komodo-mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    # ports:
    #   - 27017:27017
    volumes:
      - komodo-mongo-data:/data/db
      - komodo-mongo-config:/data/configdb
    environment:
      <<: [*timezone-env, *komodo-env, *user-permissions]
    <<: [*local-dns, *restart]
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:1.19.5@sha256:a1cceb4f971443b1e9f2a767788f663d0afb6244ee2135f7fe3fd1036af37ade
    container_name: komodo-core
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    depends_on:
      - komodo-mongo
    ports:
      - 9120:9120
    environment:
      <<: [*timezone-env, *komodo-env, *user-permissions]
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - ${BASE}/komodo/core/backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    <<: [*local-dns, *restart]
  
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5@sha256:bd79cf960ed054fe8e02384322303e462448679b1149dde48bbef151417255b1
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    environment:
      <<: [*timezone-env, *komodo-env, *user-permissions]
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    <<: [*local-dns, *restart]

  # https://github.com/librespeed/speedtest-go
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    environment:
      <<: [*librespeed-env, *user-permissions]
    ports:
      - 8030:8080 # webport mapping (host:container)
    <<: [*local-dns, *restart]
  
  # https://github.com/alexta69/metube
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2026.05.30@sha256:c5ed53d2e9f3aff3982a599aac74388d36879722b1a553a9ae0200346a321ec9
    ports:
      - 8009:8081
    volumes:
      - ${BASE}/metube/downloads:/downloads
    environment:
      <<: [*metube-env, *user-permissions]
    <<: [*local-dns, *restart]
  
  # # https://docs.n8n.io/hosting/installation/docker/
  # n8n:
  #   image: n8nio/n8n:2.19.5@sha256:b1b0c592735e24acd3cc64db83f94ef4efd8e331e47c6883249cc51cc1bea16b
  #   container_name: n8n
  #   restart: unless-stopped
  #   ports:
  #     - 8027:443
  #   environment:
  #     - GENERIC_TIMEZONE=${TIMEZONE}
  #     - TZ=${TIMEZONE}
  #     - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
  #     - N8N_RUNNERS_ENABLED=true
  #     - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
  #     - N8N_HOST=${N8N_HOST}
  #     - N8N_PORT=${N8N_PORT}
  #     - N8N_PROTOCOL=${N8N_PROTOCOL}
  #   volumes:
  #     - ${BASE}/n8n/data:/home/node/.n8n
  
  # https://nginxproxymanager.com/setup/
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.15.1@sha256:52b2c59994f3d36acfcf70a1626f29734df0ed8c71bacc0269f78b6f939858bb
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8081:81' # Admin Web Port
    volumes:
      - ${BASE}/nginx-proxy-manager/data:/data
      - ${BASE}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      <<: [*timezone-env, *user-permissions]
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    <<: [*local-dns, *restart]
  
  # https://docs.pi-hole.net/docker/
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8001:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      <<: [*pihole-env, *timezone-env, *user-permissions]
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - 'pihole_data:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      - NET_RAW
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    <<: [*cloudflare-dns, *restart]

  # https://docs.stirlingpdf.com/Installation/Docker%20Install
  stirling-pdf:
    image: stirlingtools/stirling-pdf:1.6.0@sha256:1f73a8f898fe269cbbccea3be577064dd87fc4334de349fcc5b1afa1bcebf240
    container_name: stirling-pdf
    ports:
      - 8011:8080
    environment:
      <<: [*stirling-pdf-env, *user-permissions]
    <<: [*local-dns, *restart]
  
  # https://github.com/louislam/uptime-kuma/wiki
  uptime-kuma:
    image: louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
    container_name: uptime-kuma
    volumes:
      - ${BASE}/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8026:3001
    environment:
      <<: *user-permissions
    <<: [*local-dns, *restart]
    
  
  # vagas-dev-api:
  #   image: ghcr.io/henriquesebastiao/vagas-dev/api:0.2.4@sha256:3d7e7c1cca935fa5050ead5367327a5123d863849bbe2d03697ce34273626dac
  #   container_name: vagas-dev-api
  #   restart: always
  #   env_file:
  #     - ${BASE}/vagas-dev/.env
  #   depends_on:
  #     vagas-dev-db:
  #       condition: service_healthy
  
  # vagas-dev-db:
  #   container_name: vagas-dev-db
  #   image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
  #   ports:
  #     - 8016:5432
  #   volumes:
  #     - pgdata-vagas-dev:/var/lib/postgresql/data
  #   env_file:
  #     - ${BASE}/vagas-dev/.env
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${VAGAS_DEV_POSTGRES_USER} -d ${VAGAS_DEV_POSTGRES_DB}"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 30s
  #     timeout: 10s
  # vagas-dev-web:
  #   container_name: vagas-dev-web
  #   image: nginx:1.29.8-alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de
  #   restart: always
  #   volumes:
  #     - ${BASE}/vagas-dev/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8017:80
  #   environment:
  #     - NGINX_PORT=80
  #   depends_on:
  #     - vagas-dev-api
  
  # https://github.com/dani-garcia/vaultwarden
  vaultwarden:
    image: vaultwarden/server:1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
    container_name: vaultwarden
    environment:
      <<: [*vaultwarden-env, *user-permissions]
    volumes:
      - ${BASE}/vaultwarden/data/:/data/
    ports:
      - 8019:80
    <<: [*local-dns, *restart]

  # https://www.zabbix.com/documentation/current/en/manual/installation/containers  
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:7.4.11-alpine@sha256:5f579fce86811007404d7224dc8d52a361542b333a60859f83db2844ee9e680c
    hostname: zabbix-frontend
    container_name: zabbix-frontend
    environment:
      <<: [*zabbix-env, *user-permissions]
    ports:
      - 8003:8080
    depends_on:
      - zabbix-server
      - zabbix-database
    <<: [*local-dns, *restart]

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.4.11-alpine@sha256:fb39b35ae2bdf67cf5a2abced2450c398f37dee1c59b9869e69c151c92db0034
    container_name: zabbix-server
    hostname: zabbix-server
    init: true
    environment:
      <<: [*zabbix-env, *user-permissions]
    ports:
      - 10050:10050
    depends_on:
      - zabbix-database
    <<: [*local-dns, *restart]

  zabbix-agent:
    image: zabbix/zabbix-agent2:7.4.11-alpine@sha256:e81391e2788408167b445e98806362a7a201f344d685f4d1203ea4eef65d0104
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    init: true
    environment:
      <<: [*zabbix-env, *user-permissions]
    <<: [*local-dns, *restart]

  zabbix-database:
    image: postgres:13.18-alpine3.20@sha256:77815c1f18ae761b0e503503a494475a03149d7ce544934ccecdbafdb3956c94
    container_name: zabbix-database
    hostname: zabbix-database
    environment:
      <<: [*zabbix-env, *user-permissions]      
    volumes:
      - ${BASE}/zabbix/data:/var/lib/postgresql/data
    <<: [*local-dns, *restart]

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
  komodo-mongo-data:
  komodo-mongo-config:
  model-cache:
  pihole_data:
  pgdata-vagas-dev:
