# Este arquivo docker compose configura todos os serviços que utilizo em produção no meu servidor pessoal
# 
# Informações úteis para administração dos containers:
# - Os containers estão dispostos em ordem alfabéticas neste arquivo
# - No início de cada serviço há um ou mais links para a documentação ou tutoriais de como configurar cada serviço

services:

  # https://www.audiobookshelf.org/docs#docker-compose-install
  # https://www.audiobookshelf.org/docs#docker-compose-upgrade
  # https://www.audiobookshelf.org/docs#env-configuration
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.34.0@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /mnt/hd_externo/containers/audiobookshelf/audiobooks:/audiobooks
      - /mnt/hd_externo/containers/audiobookshelf/podcasts:/podcasts
      - /mnt/hd_externo/containers/audiobookshelf/config:/config
      - /mnt/hd_externo/containers/audiobookshelf/metadata:/metadata
    environment:
      - TZ=${TIMEZONE}
    restart: always

  # https://github.com/linuxserver/docker-calibre-web
  # https://github.com/janeczku/calibre-web
  calibre-web:
    image: linuxserver/calibre-web:0.6.26@sha256:c1b0068188fd9bb5237988623a8a930401384b183e073e193ef8ec1e136aef8d
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/hick/homelab/containers/calibre-web/config:/config
      - /home/hick/homelab/containers/calibre-web/books:/books
    ports:
      - 8024:8083
    restart: unless-stopped

  # https://hub.docker.com/r/cloudflare/cloudflared
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
  
  downtify:
    image: ghcr.io/henriquesebastiao/downtify:2.6.0@sha256:7a71e6b510b28a5f34dec033ca52a3a7b0713cb44924d77101961a4c2697aabb
    container_name: downtify
    restart: unless-stopped
    ports:
      - 8020:8000
    volumes:
      - /home/hick/homelab/containers/jellyfin/media/downtify:/downloads
      - /home/hick/homelab/containers/downtify/data:/data

  # https://dozzle.dev/guide/what-is-dozzle
  # https://github.com/amir20/dozzle
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.5.1@sha256:2f8d5c2b6181533a58246313b1d840a69ae04e6c1010e2f6bb52c2228342b443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8005:8080
  
  # https://github.com/linuxserver/docker-duplicati
  # https://docs.duplicati.com/
  #
  # Diretórios de backups
  # --------------------------------------------
  # Drive                           -> Home Server
  # --------------------------------------------
  # Backups/duplicati/calibre/      -> $HOME/homelab/containers/calibre-web/
  duplicati:
    image: linuxserver/duplicati:2.3.0@sha256:e13e45989514928a22c5209019c51af8aa83233f378e32498fe8a0f6ec10cc7b
    container_name: duplicati
    restart: unless-stopped
    privileged: true
    ports:
      - 8018:8200
    volumes:
      - /home/hick/homelab/containers/duplicati/config:/config
      - /home/hick/backups:/backups
      - /:/source:rw
    user: '0'
    environment:
      DUPLICATI__WEBSERVICE_PASSWORD: ${DUPLICATI__WEBSERVICE_PASSWORD}
      PUID: 0
      PGID: 0
      SETTINGS_ENCRYPTION_KEY: ${SETTINGS_ENCRYPTION_KEY}
      TZ: ${TIMEZONE}

  # https://filebrowser.org/installation.html
  # https://github.com/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser:v2.63.2@sha256:4dce87308b9f9cfbcf8d0a284fc9565d2b515530a6bae2d920b388161e093f26
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0"
    ports:
      - 8015:80
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - /home/hick:/data
      - /mnt/hd_externo:/data/hd
    environment:
      - FB_ROOT=/data
      - FB_NOAUTH=true
  
  # https://github.com/FreshRSS/FreshRSS#installation
  # https://freshrss.org/
  freshrss:
    image: freshrss/freshrss:1.28.1@sha256:9100f649f5c946f589f54cdb9be7a65996528f48f691ef90eb262a0e06e5a522
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8036:80
    volumes:
      - /home/hick/homelab/containers/freshrss/data:/var/www/FreshRSS/data
      - /home/hick/homelab/containers/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: ${TIMEZONE}
      CRON_MIN: '2,32'
      FRESHRSS_INSTALL: |-
        --api-enabled
        --default-user hick
        --language pt-BR
      FRESHRSS_USER: |-
        --api-password ${FRESHRSS_PASSWORD}
        --email ${FRESHRSS_EMAIL}
        --language pt-BR
        --password ${FRESHRSS_PASSWORD}
        --user ${FRESHRSS_USER}

  # https://github.com/glanceapp/glance
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/glance/config:/app/config
      - /home/hick/homelab/containers/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8007:8080
    env_file: /home/hick/homelab/containers/glance/.env
  
  glance-mila:
    container_name: glance-mila
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - /home/hick/homelab/containers/glance-mila/config:/app/config
      - /home/hick/homelab/containers/glance-mila/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8014:8080
    env_file: /home/hick/homelab/containers/glance-mila/.env
  
  # https://go2rtc.org/
  # https://github.com/AlexxIT/go2rtc
  go2rtc: # HTTP Port: 1984, RSTP Port: 8554, WebRTC Port: 8554
    image: alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae
    container_name: go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=${TIMEZONE}  # timezone in logs
    volumes:
      - "/home/hick/homelab/containers/go2rtc/config:/config"   # folder for go2rtc.yaml file (edit from WebUI)

  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    restart: unless-stopped
    ports:
      - 8004:3000
    user: '0'
    volumes:
      - /home/hick/homelab/containers/grafana:/var/lib/grafana
  
  # https://docs.immich.app/install/docker-compose
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
    volumes:
      - /home/hick/homelab/containers/immich/data:/data # Directory where photos and videos are stored
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 8025:2283
    depends_on:
      - immich-redis
      - immich-db
      - immich-machine-learning
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    hostname: redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-db:
    container_name: immich-postgres
    hostname: database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:8d292bdb796aa58bbbaa47fe971c8516f6f57d6a47e7172e62754feb6ed4e7b0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /home/hick/homelab/containers/immich-db/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
  
  # https://jellyfin.org/docs/general/installation/container/
  jellyfin:
    image: jellyfin/jellyfin:10.11.8@sha256:1694ff069f0c9dafb283c36765175606866769f5d72f2ed56b6a0f1be922fc37
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/hick/homelab/containers/jellyfin/config:/config
      - /home/hick/homelab/containers/jellyfin/cache:/cache
      - type: bind
        source: /home/hick/homelab/containers/jellyfin/media
        target: /media
      - type: bind
        source: /mnt/hd_externo/Videos
        target: /media/hd/Videos
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://server.local:8096
  
  # https://komo.do/docs/setup/mongo
  komodo-mongo:
    image: mongo:8.2.7@sha256:7abfba0d07c9330373f8173981ea4d09cd8a82cdf0e86ccaf7008848d1d24f62
    container_name: komodo-mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - komodo-mongo-data:/data/db
      - komodo-mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:1.19.5@sha256:a1cceb4f971443b1e9f2a767788f663d0afb6244ee2135f7fe3fd1036af37ade
    container_name: komodo-core
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    env_file: /home/hick/homelab/containers/komodo/.env
    depends_on:
      - komodo-mongo
    ports:
      - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: admin
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - /home/hick/homelab/containers/komodo/core/backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
  
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5@sha256:bd79cf960ed054fe8e02384322303e462448679b1149dde48bbef151417255b1
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    env_file: /home/hick/homelab/containers/komodo/.env
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}

  # https://github.com/librespeed/speedtest-go
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      #TITLE: "LibreSpeed"
      #TELEMETRY: "false"
      #ENABLE_ID_OBFUSCATION: "false"
      #REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    ports:
      - 8030:8080 # webport mapping (host:container)
  
  # https://github.com/alexta69/metube
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2026.04.28@sha256:caf21da7d83a4003b429ef1126e9c1499f36f8401a1f8a7b158f70b94ade8edd
    restart: unless-stopped
    ports:
      - 8009:8081
    volumes:
      - /home/hick/homelab/containers/metube/downloads:/downloads
    environment:
      - DOWNLOAD_MODE=sequential
      - DEFAULT_THEME=dark
  
  # https://docs.n8n.io/hosting/installation/docker/
  n8n:
    image: n8nio/n8n:2.18.5@sha256:2d70fafea7c0c397f40df30daa31243c0bff590e9e87e0430398e7cb4d3d8d0b
    container_name: n8n
    restart: unless-stopped
    ports:
      - 8027:443
    environment:
      - GENERIC_TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
    volumes:
      - /home/hick/homelab/containers/n8n/data:/home/node/.n8n
  
  # https://nginxproxymanager.com/setup/
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8081:81' # Admin Web Port
    volumes:
      - /home/hick/homelab/containers/nginx-proxy-manager/data:/data
      - /home/hick/homelab/containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  
  # https://docs.pi-hole.net/docker/
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.04.1@sha256:1c32c36b862a12762656b6471c854cebc01fe945639ba3a893611337c2c95e99
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8001:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: ${TIMEZONE}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD:-pihole-pass}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/home/hick/homelab/containers/pihole/etc:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      - NET_RAW
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    networks:
      dns_network:
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
  
  # https://github.com/linuxserver/docker-qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4@sha256:c9990949e968e99333f47f49da7d16e81ba6e1469c8c46807a65b984c9e8b6ff
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8033
      - TORRENTING_PORT=6881
    volumes:
      - /home/hick/homelab/containers/qbittorrent/config:/config
      - /home/hick/homelab/containers/qbittorrent/downloads:/downloads #optional
    ports:
      - 8033:8033
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  # https://docs.speedtest-tracker.dev/
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:1.14.0@sha256:2f2360315ab5144234b9b81fea46a8777045efcb455da50d2ee87d440af8e3b1
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8008:80
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:h/7HdA9fMLDluj0fJ4NcG13CquLdgJTs9062lfXnmAs=
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=${TIMEZONE}
      - DISPLAY_TIMEZONE=${TIMEZONE}
      - APP_DEBUG=true
      - SPEEDTEST_SCHEDULE=*/30 * * * *
      # - SPEEDTEST_SERVERS=
    volumes:
      - /home/hick/homelab/containers/speedtest-tracker/config:/config
      - /home/hick/homelab/containers/speedtest-tracker/config/keys:/config/keys
  
  # https://github.com/syncthing/syncthing/blob/main/README-Docker.md
  syncthing:
    image: syncthing/syncthing:2.0.16@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/hick/homelab/containers/syncthing:/var/syncthing
    ports:
      - 8032:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  # https://docs.stirlingpdf.com/Installation/Docker%20Install
  stirling-pdf:
    image: stirlingtools/stirling-pdf:1.6.0@sha256:1f73a8f898fe269cbbccea3be577064dd87fc4334de349fcc5b1afa1bcebf240
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - 8011:8080
    environment:
      - LANGS=pt_BR
      - DISABLE_ADDITIONAL_FEATURES=true
  
  # https://docs.umami.is/docs/install
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest@sha256:e3f80c0625aad7179b49da27d475357cabb1068b8cacd9a792cfd6966888b123
    container_name: umami
    ports:
      - 8006:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ljVRotlgItt2dHR8TgvXvfKAfvf6AFiydmNfvKx-7oE
    depends_on:
      umami-db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umami -d umami"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # https://github.com/louislam/uptime-kuma/wiki
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
    container_name: uptime-kuma
    volumes:
      - /home/hick/homelab/containers/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8026:3001
    restart: always
  
  vagas-dev-api:
    image: ghcr.io/henriquesebastiao/vagas-dev/api:0.2.4@sha256:3d7e7c1cca935fa5050ead5367327a5123d863849bbe2d03697ce34273626dac
    container_name: vagas-dev-api
    restart: always
    env_file:
      - /home/hick/homelab/containers/vagas-dev/.env
    depends_on:
      vagas-dev-db:
        condition: service_healthy
  
  vagas-dev-db:
    container_name: vagas-dev-db
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    ports:
      - 8016:5432
    volumes:
      - pgdata-vagas-dev:/var/lib/postgresql/data
    env_file:
      - /home/hick/homelab/containers/vagas-dev/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VAGAS_DEV_POSTGRES_USER} -d ${VAGAS_DEV_POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  vagas-dev-web:
    container_name: vagas-dev-web
    image: nginx:1.29.8-alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de
    restart: always
    volumes:
      - /home/hick/homelab/containers/vagas-dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8017:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - vagas-dev-api
  
  # https://github.com/dani-garcia/vaultwarden
  vaultwarden:
    image: vaultwarden/server:1.35.8@sha256:c4f6056fe0c288a052a223cecd263a90d1dda1a0177bb5b054a363a6c7b211d9
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.local"
    volumes:
      - /home/hick/homelab/containers/vaultwarden/data/:/data/
    ports:
      - 8019:80

  # https://www.zabbix.com/documentation/current/en/manual/installation/containers  
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:7.4.9-alpine@sha256:4171f82155ce4c0a177130c4ad418d48bbe81a431dc10d0678fbe28a9bf17779
    hostname: zabbix-frontend
    container_name: zabbix-frontend
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - 8003:8080
    depends_on:
      - zabbix-server
      - zabbix-database

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.4.9-alpine@sha256:92d280d694a2192dc0ca9e4677abd6ae2d68132d6739d5fcbde10b58f544e5d4
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    init: true
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - 10050:10050
    depends_on:
      - zabbix-database

  zabbix-agent:
    image: zabbix/zabbix-agent2:7.4.9-alpine@sha256:d116686102fc2e479b66c10719485d2dd3650ae70442ae4bac3262466ef2eba7
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    init: true
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server

  zabbix-database:
    image: postgres:13.18-alpine3.20@sha256:77815c1f18ae761b0e503503a494475a03149d7ce544934ccecdbafdb3956c94
    container_name: zabbix-database
    hostname: zabbix-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - /home/hick/homelab/containers/zabbix/data:/var/lib/postgresql/data

networks:
  dns_network:
    driver: bridge

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:
  komodo-mongo-data:
  komodo-mongo-config:
  model-cache:
  umami-db-data:
  pgdata-vagas-dev:
