- name: Início
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
  
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
        - type: calendar
          first-day-of-week: sunday

    - size: full
      widgets:
        - type: search
          search-engine: duckduckgo
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}
        - type: bookmarks
          groups:
            - links:
                - title: Agenda
                  url: https://calendar.google.com
                - title: Email
                  url: https://mail.google.com/mail/u/0/#inbox
                - title: Drive
                  url: https://drive.google.com/drive/u/0/my-drive
            - title: Cursos
              color: 200 50 50
              links:
                - title: IFRS
                  url: https://moodle.ifrs.edu.br/
                - title: IFMS
                  url: https://cursoslivres.ifms.edu.br/
                - title: IFRO
                  url: https://mooc.ifro.edu.br/
                - title: FGV
                  url: https://educacao-executiva.fgv.br/cursos/gratuitos
                - title: Bradesco
                  url: https://www.ev.org.br/
                - title: Unicamp
                  url: https://moocs.ggte.unicamp.br/courses
                - title: Santander
                  url: https://www.santanderopenacademy.com/pt_br/index.html
                - title: Escola Virtual
                  url: https://www.escolavirtual.gov.br/
            - title: Seletivos e Concursos
              color: 22 77 41
              links:
                - title: Aripuanã
                  url: https://www.aripuana.mt.gov.br/#/transparencia/finder/MTI5
                - title: ALE-RO 2025
                  url: https://conhecimento.fgv.br/concursos/alero25
    - size: small
      widgets:
        - type: weather
          location: Cotriguaçu, Brazil
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
