network:
  version: 2
  ethernets:
    eno1:
      dhcp4: true
    wlp1s0:
      dhcp4: no
      addresses:
        - 172.16.0.2/24
      routes:
        - to: default
          via: 172.16.0.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 1.0.0.1
