- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    # - size: small
    #   widgets:


    - size: full
      widgets:       
        - type: docker-containers
          containers:
            adminer-manejo:
              hide: true
            client-dotum:
              hide: true
            zabbix-database:
              parent: zabbix
              name: Database
            confy-redis:
              hide: true
            db-manejo:
              hide: true
            app-dotum:
              hide: true
            app-manejo:
              hide: true
            calibre-web:
              name: Calibre Web
              url: http://calibre.local
              icon: di:calibre-web
            zabbix-agent:
              parent: zabbix
              name: Agent
            app-poupy:
              hide: true
            zabbix-server:
              id: zabbix
              name: Zabbix
              url: http://zabbix.local
              icon: di:zabbix
            komodo-core:
              id: komodo
              name: Komodo
              url: https://komodo.local
              icon: di:komodo
            komodo-mongo:
              parent: komodo
              name: MongoDB
            komodo-periphery:
              parent: komodo
              name: Komodo Periphery
            db-poupy:
              hide: true
            db-dotum:
              hide: true
            duplicati:
              name: Duplicati
              url: http://172.16.0.2:8018
              icon: di:duplicati
            prometheus-manejo:
              hide: true
            web-manejo:
              hide: true
            glance:
              hide: true
            glance-mila:
              hide: true
            postgres-projects:
              hide: true
            confy-server:
              hide: true
            grafana-manejo:
              hide: true
            tempo-manejo:
              hide: true
            web-confy-server:
              hide: true
            stirling-pdf:
              name: Stirling PDF
              url: http://stirling.local/?lang=pt_BR
              icon: di:stirling-pdf
            filebrowser:
              name: File Browser
              url: http://filebrowser.local
              icon: di:filebrowser
            pihole:
              name: Pi-hole
              url: http://pihole.local/admin/
              icon: di:pi-hole
            uptime-kuma:
              name: Uptime Kuma
              url: http://uptime.local/dashboard
              icon: di:uptime-kuma
            zabbix-frontend:
              parent: zabbix
              name: Front End
            n8n:
              name: n8n
              url: https://n8n.local
              icon: di:n8n
            grafana:
              name: Grafana
              url: http://grafana.local
              icon: di:grafana
            cloudflared:
              name: Cloudflared
              icon: di:cloudflare
            dozzle:
              name: Dozzle
              url: http://dozzle.local
              icon: di:dozzle
            jellyfin:
              name: Jellyfin
              url: http://jellyfin.local/web/#/home.html
              icon: di:jellyfin
            vaultwarden:
              name: Vaultwarden
              url: https://vault.henriquesebastiao.com
              icon: auto-invert di:vaultwarden
            librespeed:
              name: LibreSpeed
              url: http://librespeed.local
              icon: di:librespeed
            metube:
              name: MeTube
              url: http://metube.local
              icon: sh:metube
            freshrss:
              name: FreshRSS
              url: http://freshrss.local
              icon: sh:freshrss
            n8n-postgres-chat-memory:
              hide: true
            nginx-proxy-manager:
              name: Nginx Proxy Manager
              url: http://proxy.local
              icon: sh:nginx-proxy-manager
            vagas-dev-api:
              id: vagas-dev
              name: Vagas Dev
              icon: si:fastapi
            vagas-dev-db:
              parent: vagas-dev
              name: Database
            vagas-dev-web:
              parent: vagas-dev
              name: Nginx
            downtify:
              name: Downtify
              url: http://downtify.local
              icon: si:fastapi
            navidrome:
              name: Navidrome
              url: http://navidrome.local
              icon: di:navidrome
        - type: bookmarks
          groups:
            - title:
              links:
                - title: Agenda
                  url: https://calendar.google.com/calendar/u/0/r
                - title: Email
                  url: https://mail.google.com/mail/u/0/#inbox
                - title: Drive
                  url: https://drive.google.com/drive/u/0/my-drive
            - title: Vagas
              links:
                - title: LinkedIn
                  url: https://www.linkedin.com/
                - title: Gupy
                  url: https://portal.gupy.io/my/applications
                - title: Glassdoor
                  url: https://www.glassdoor.com.br/
                - title: Sólides
                  url: https://perfil.vagas.solides.com.br/
                - title: Aripuanã
                  url: https://www.aripuana.mt.gov.br/#/transparencia/finder/MTI5
                - title: ALE-RO
                  url: https://conhecimento.fgv.br/concursos/alero25
                - title: Correios
                  url: https://prosel.correios.com.br/concursos/detalharconcurso/1213
                - title: PCI Concursos
                  url: https://www.pciconcursos.com.br/
            - title: Documentação
              links:
                - title: Python
                  url: https://docs.python.org/pt-br/3.14/
                - title: FastAPI
                  url: https://fastapi.tiangolo.com/
                - title: Django
                  url: https://docs.djangoproject.com/pt-br/
                - title: MDN
                  url: https://developer.mozilla.org
                - title: Next.js
                  url: https://nextjs.org/docs
                - title: Micropython
                  url: https://docs.micropython.org/en/latest/
                - title: Docker
                  url: https://docs.docker.com
            - title: Ferramentas
              links:
                - title: Code Server
                  url: https://code.local/
                - title: Claude
                  url: https://claude.ai
                - title: PyPi
                  url: https://pypi.org/
                - title: GitHub
                  url: https://github.com
                - title: Cloudflare
                  url: https://dash.cloudflare.com/
                - title: Docker Hub
                  url: https://hub.docker.com/
                - title: Canva
                  url: https://www.canva.com/
                - title: Facebook Ads
                  url: https://business.facebook.com
                - title: Fiverr
                  url: https://br.fiverr.com/
            - title: Estudos
              color: 200 50 50
              links:
                - title: Udemy
                  url: https://www.udemy.com/
                - title: CS50x
                  url: https://cs50.harvard.edu/x/
                - title: CS50x Progress
                  url: https://cs50.me/cs50x
                - title: Roadmap.sh
                  url: https://roadmap.sh/dashboard
                - title: Seletivos IFMT
                  url: https://seletivo.ifmt.edu.br/
            - title: Technology
              color: 203 83 65
              links:
                - title: Cheat Sheets
                  url: https://cheatsheets.zip
                - title: Pwned
                  url: https://haveibeenpwned.com
                - title: Cloudflare
                  url: https://dash.cloudflare.com/
            - title: Equipamentos
              color: 146 63 51
              links:
                - title: CHR
                  url: https://chr.henriquesebastiao.com
                - title: HS-Switch
                  url: https://switch.local
                - title: HS-Groove
                  url: https://groove.local
                - title: ST-Switch
                  url: http://chr.henriquesebastiao.com:55002
                - title: ST-AP
                  url: http://chr.henriquesebastiao.com:55003
                - title: Antena do Sítio
                  url: https://rx-sitio.local
                - title: Inversor
                  url: https://inversor.local
            - title: Analytics
              color: 296 85 35
              links:
                - title: GoatCounter
                  url: https://henriquesebastiao.goatcounter.com
            - title: Others
              color: 237 51 59
              links:
                - title: Flightradar24
                  url: https://www.flightradar24.com/-10.21,-59.46/9
                - title: Carvalima
                  url: https://cliente.carvalima.com.br/dashboard
            - title: Serviços
              links:
                - title: Energisa
                  url: https://servicos.energisa.com.br/home
                - title: DAE
                  url: https://aripuana.cogesan.com.br/portal
                - title: Banco Central
                  url: https://meubc.bcb.gov.br/meubc/

    - size: small
      widgets:        
        - type: server-stats
          servers:
            - type: local
              name: Servidor
              hide-mountpoints-by-default: true
              hide-swap: true
              mountpoints:
                "/":
                  name: Root
                  hide: false
        - type: dns-stats
          service: pihole-v6
          url: http://172.16.0.2:8001
          password: 35218785
          allow-insecure: true
          hour-format: 24h
