- name: Projects
  columns:
    - size: small
      widgets:
      - type: monitor
        cache: 1m
        title: Sites
        style: compact
        sites:
          - title: Confy Server
            url: https://confy-server.henriquesebastiao.com/docs
          - title: Dotum Server
            url: https://dotum.henriquesebastiao.com
          - title: Dotum Web
            url: https://dotum-web.henriquesebastiao.com
          - title: Poupy
            url: https://poupy.henriquesebastiao.com
          - title: Manejo
            url: https://manejo.henriquesebastiao.com
          - title: Netmikro
            url: https://netmikro.henriquesebastiao.com/en/latest
          - title: Skyport
            url: https://skyport.henriquesebastiao.com/en/latest
          - title: Downtify
            url: https://downtify.henriquesebastiao.com
          - title: Status
            url: https://status.henriquesebastiao.com/status/projetos-pessoais
    
    - size: full
      widgets:
        - type: docker-containers
          containers:
            adminer-manejo:
              parent: manejo
              name: Adminer
            calibre-web:
              hide: true
            client-dotum:
              parent: dotum
              name: Streamlit
            zabbix-database:
              hide: true
            confy-redis:
              parent: confy
              name: Redis
            db-manejo:
              parent: manejo
              name: Database
            app-dotum:
              id: dotum
              name: Dotum
              url: http://server.local:9004
              icon: si:streamlit
            app-manejo:
              id: manejo
              name: Manejo
              url: http://server.local:9000
              icon: si:fastapi
            zabbix-agent:
              hide: true
            downtify:
              name: Downtify
              url: http://server.local:9002
              icon: si:fastapi
            app-poupy:
              id: poupy
              name: Poupy
              url: https://poupy.henriquesebastiao.com
              icon: si:django
            zabbix-server:
              hide: true
            db-poupy:
              parent: poupy
              name: Database
            db-dotum:
              parent: dotum
              name: Database
            filebrowser:
              hide: true
            prometheus-manejo:
              parent: manejo
              name: Prometheus
            umami-db:
              hide: true
            web-manejo:
              parent: manejo
              name: Nginx
            glance:
              hide: true
            postgres-projects:
              name: Postgres
              icon: si:postgresql
            confy-server:
              id: confy
              name: Confy Server
              url: http://server.local:9005/docs
              icon: si:fastapi
            grafana-manejo:
              parent: manejo
              name: Grafana
            duplicati:
              hide: true
            homeassistant:
              hide: true
            tempo-manejo:
              parent: manejo
              name: Tempo
            web-confy-server:
              parent: confy
              name: Nginx
            web-check:
              hide: true
            it-tools:
              hide: true
            stirling-pdf:
              hide: true
            excalidraw:
              hide: true
            portainer:
              hide: true
            speedtest-tracker:
              hide: true
            pihole:
              hide: true
            pinepods:
              hide: true
            pinepods-valkey:
              hide: true
            pinepods-db:
              hide: true
            uptime-kuma:
              hide: true
            zabbix-frontend:
              hide: true
            nextcloud:
              hide: true
            grafana:
              hide: true
            cloudflared:
              hide: true
            dozzle:
              hide: true
            umami:
              hide: true
            jellyfin:
              hide: true
            ocular-backend:
              hide: true
            ocular-frontend:
              hide: true
            ocular-nginx:
              hide: true
            wallos:
              hide: true
            beaverhabits:
              hide: true
            vaultwarden:
              hide: true
    - size: small
      widgets:
        - type: releases
          cache: 1d
          show-source-icon: true
          repositories:
            - fastapi/fastapi
            - pydantic/pydantic
            - streamlit/streamlit
            - Kludex/uvicorn
            - astral-sh/ruff
            - taskipy/taskipy
            - sqlalchemy/alembic
            - sqlalchemy/sqlalchemy
            - pytest-dev/pytest
            - locustio/locust